from enum import Enum

class FileFilter(Enum):
    TEXT_FILES = "Metin Dosyaları (*.txt)"
    IMAGE_FILES = "Resim Dosyaları (*.png *.jpg *.jpeg)"
    DOCUMENTS = "Belge Dosyaları (*.docx *.xlsx *.pdf)"
    JSON_FILES = "JSON Dosyaları (*.json)"
    CSV_FILES = "CSV Dosyaları (*.csv)"
    XML_FILES = "XML Dosyaları (*.xml)"
    HTML_FILES = "HTML Dosyaları (*.html *.htm)"
    AUDIO_FILES = "Ses Dosyaları (*.mp3 *.wav *.ogg)"
    VIDEO_FILES = "Video Dosyaları (*.mp4 *.avi *.mov)"
    ARCHIVE_FILES = "Arşiv Dosyaları (*.zip *.rar)"
    PYTHON_FILES = "Python Dosyaları (*.py)"
    JAVA_FILES = "Java Dosyaları (*.java)"
    CSHARP_FILES = "C# Dosyaları (*.cs)"
    CPP_FILES = "C++ Dosyaları (*.cpp *.hpp)"
    PHP_FILES = "PHP Dosyaları (*.php)"
    SQL_FILES = "SQL Dosyaları (*.sql)"
    SHELL_FILES = "Shell Script Dosyaları (*.sh)"
    ANIME_URL_FILES = "Anime URL Dosyaları (*.aurl)"
    BATCH_FILES = "Batch Script Dosyaları (*.bat *.cmd)"
    YAML_FILES = "YAML Dosyaları (*.yaml *.yml)"
    MARKDOWN_FILES = "Markdown Dosyaları (*.md)"
    PDF_FILES = "PDF Dosyaları (*.pdf)"
    WORD_FILES = "Word Dosyaları (*.docx)"
    EXCEL_FILES = "Excel Dosyaları (*.xlsx)"
    POWERPOINT_FILES = "PowerPoint Dosyaları (*.pptx)"
    AUDIO_VIDEO_FILES = "Ses ve Video Dosyaları (*.mp3 *.wav *.ogg *.mp4 *.avi *.mov)"
    PROGRAMMING_FILES = "Programlama Dosyaları (*.py *.java *.cs *.cpp *.php *.sh *.bat)"
    CONFIG_FILES = "Yapılandırma Dosyaları (*.xml *.yaml *.yml)"
    DOCUMENT_FILES = "Belge Dosyaları (*.docx *.xlsx *.pdf *.pptx)"
    ALL_FILES = "Tüm Dosyalar (*)"